In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression

In [40]:
X,y = make_regression(n_samples=100, n_features=1, n_informative=1, n_targets=1,noise=20,random_state=13)
type(X)

numpy.ndarray

In [41]:
df = pd.read_csv('../election data/Bihar_Election_Results (1) (2).csv')
df = df.dropna()
x = df.iloc[:,1:4:3]
y =df.iloc[:,3:4] 
x= np.array(x)
y = np.array(y)
x

array([[ 1],
       [ 2],
       [ 3],
       ...,
       [17],
       [18],
       [19]])

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=2)

<IPython.core.display.Javascript object>

# custom created gradeant decent

In [48]:
# custom created gradeant decent
class Gdreg:
    def __init__(self,learning_rate,epochs):
        self.m = 100
        self.b = -120
        self.lr = learning_rate
        self.epochs = epochs
    def fit(self,X,y):
       
        for i in range(self.epochs):
            loss_slope_b = -2 * np.sum(y - self.m*X.ravel() - self.b)
            loss_slope_m = -2 * np.sum((y - self.m*X.ravel() - self.b)*X.ravel())
            
            self.b = self.b - (self.lr * loss_slope_b)
            self.m = self.m - (self.lr * loss_slope_m)
        print(self.m,self.b)
        
    def predict(self,x_test):
        return self.m * x_test +self.b
            

In [49]:
gd1 = Gdreg(0.001,85)

In [45]:
gd1.fit(x_train.reshape(1,-1),y_train.reshape(1,-1))

5.453921465939716e+276 4.925299517315098e+275


In [46]:
gd1.predict(x_test)


array([[2.23082158e+277],
       [2.23082158e+277],
       [5.94645142e+276],
       ...,
       [1.14003729e+277],
       [7.13935090e+277],
       [6.59395875e+277]])

# sklearn regression

In [50]:
# sklearn regression
lr = LinearRegression()

<IPython.core.display.Javascript object>

In [51]:
lr.fit(x_train,y_train)

LinearRegression()

In [52]:
lr.coef_

array([[-1840.92438305]])

In [53]:
lr.intercept_

array([23518.67271957])

In [54]:
lr.predict(x_test)

array([[16154.97518738],
       [16154.97518738],
       [21677.74833652],
       ...,
       [19836.82395348],
       [ -413.34426005],
       [ 1427.580123  ]])

In [56]:
pre = lr.predict(x_test)
from sklearn.metrics import r2_score
r2_score(y_test,pre)

0.3401125908054059

0.3401125908054059