In [18]:
import pandas as pd

In [19]:
df = pd.read_csv('../election data/Bihar_Election_Results (1) (2).csv')
df

Election Year  Position                     Name  Votes Votes %  \
0              2010         1             Rajesh Singh  42289  29.40%   
1              2010         2    Mukesh Kumar Kushwaha  27618  19.20%   
2              2010         3  Dheerendra Pratap Singh  20886  14.50%   
3              2010         4           Irshad Hussain  17747  12.40%   
4              2010         5      Deep Narayan Mahato  14047   9.80%   
...             ...       ...                      ...    ...     ...   
12296      2005-Feb        15  Chandeshwar Prasad Gupt    534   0.60%   
12297      2005-Feb        16             Tirpit Singh    498   0.60%   
12298      2005-Feb        17        Surendra Rajbansi    437   0.50%   
12299      2005-Feb        18       Nawin Kumar Paswan    415   0.50%   
12300      2005-Feb        19               Ajay Kumar    407   0.50%   

                          Party        AC name  AC No  
0           Janata Dal (United)  Valmiki Nagar      1  
1          Rashtriya Janata Dal  Valmiki Nagar      1  
2           Bahujan Samaj Party  Valmiki Nagar      1  
3      Indian National Congress  Valmiki Nagar      1  
4                   Independent  Valmiki Nagar      1  
...                         ...            ...    ...  
12296               Independent         Chakai    243  
12297               Independent         Chakai    243  
12298               Independent         Chakai    243  
12299               Independent         Chakai    243  
12300               Independent         Chakai    243  

[12301 rows x 8 columns]

In [20]:
from sklearn.model_selection import train_test_split


In [21]:
x = df.iloc[:,1:4:3]
y =df.iloc[:,3:4] 
x

Position
0             1
1             2
2             3
3             4
4             5
...         ...
12296        15
12297        16
12298        17
12299        18
12300        19

[12301 rows x 1 columns]

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)
x_test

Position
1373          4
8639          4
1850          1
2641         13
2880          5
...         ...
4757         19
3465          9
10373         2
4710         13
1830         12

[2461 rows x 1 columns]

In [30]:
class mylr():
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,x_train,y_train):
        num = 0
        den = 0
        for i in range(x_train.shape[0]):
            # foruma of loss function = (x_train(I)-x_train.mean())*(y_tarin[i]-y_train.mean())/[x_train[i]-x_train.mean()**2]
            num = num + ((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den = den + ((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))
        self.m = num/den
        self.b = y_train.mean()- (self.m*x_train.mean())
        print(self.m,self.b)
    def predict(self,x_test):
        y = self.m*x_test + self.b
        return y
            

In [31]:
lr = mylr()

In [32]:
lr.fit(x_train.values.reshape(-1,1),y_train.values.reshape(-1,1))
lr.predict(x_test)

[-1840.92438305] [23518.67271957]


Position
1373   16154.975187
8639   16154.975187
1850   21677.748337
2641    -413.344260
2880   14314.050804
...             ...
4757  -11458.890558
3465    6950.353272
10373  19836.823953
4710    -413.344260
1830    1427.580123

[2461 rows x 1 columns]

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
lro = LinearRegression()

In [35]:
#lro.fit(x_train,y_train.values.ravel())
lro.fit(x_train,y_train)

LinearRegression()

In [36]:
lro.coef_

array([[-1840.92438305]])

In [37]:
lro.intercept_

array([23518.67271957])

In [38]:
lro.predict(x_test)

array([[16154.97518738],
       [16154.97518738],
       [21677.74833652],
       ...,
       [19836.82395348],
       [ -413.34426005],
       [ 1427.580123  ]])